FROM node:22.20.0-alpine
RUN apk add --no-cache git
RUN corepack enable
WORKDIR /usr/src/app

COPY package*.json pnpm-lock.yaml ./

RUN pnpm config set store-dir .pnpm-store

RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
# CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]