services:
  pwa_app:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile.dev
    tty: true
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - pnpm_store:/usr/src/app/.pnpm-store
    ports:
      - "${HOST_PORT}:3000"

volumes:
  node_modules:
  pnpm_store: