services:
  pwa:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
      args:
        - VITE_API_URL_ARG=${VITE_API_URL}
    image: poc-pwa-app:0.1.0
    env_file: .env.production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:80"
      - "443:443"
    networks:
      - pwa_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  pwa_network:
    driver: bridge